- hosts: server
  vars:
    wr_dir: ~/webrecorder
    wr_app_host: ''
    wr_content_host: '{{ wr_app_host }}'

    wr_remote_browsers:
      - 'chrome:53'
      - 'firefox:49'

    cert_key_name: '{{ wr_app_host }}'

    certbot_email: 'test@example.com'

    nginx_conf_template: "{{ playbook_dir }}/templates/nginx.conf"
    nginx_vhost_template: "{{ playbook_dir }}/templates/wrhost.conf"
    nginx_remove_default_vhost: true

    nginx_ppa_use: true
    nginx_ppa_version: stable

    certbot_auto_renew: true
    certbot_auto_renew_user: "{{ ansible_user }}"
    certbot_auto_renew_hour: 12
    certbot_auto_renew_minute: 26

    nginx_vhosts:
      - server_name: "{{ wr_content_host }}"
        filename: "{{ wr_content_host }}.conf"
        include_ws: false

      - server_name: "{{ wr_app_host }}"
        filename: "{{ wr_app_host }}.conf"
        include_ws: true

    pip_install_packages:
      - name: docker-compose

  roles:
    - { role: geerlingguy.pip, become: true, become_user: root }
    - { role: certbot, become: true, become_user: root, when: "wr_app_host != ''" }
    - { role: geerlingguy.nginx, become: true, become_user: root, when: "wr_app_host != ''" }
    - { role: geerlingguy.docker, become: true, become_user: root }
    - { role: webrecorder_init }

