---
  - name: 'Install Certbot'
    include_role:
      #name: geerlingguy.certbot
      name: ansible-role-certbot

  - block:
      - import_tasks: run.yml

    rescue:
      - name: 'Stop nginx'
        service: name=nginx state=stopped

      - import_tasks: run.yml


